criaCartao('Tema', 'Qual é o nome completo do personagem principal masculino?', 'Stefan Salvatore');
criaCartao('Tema', 'Quem interpreta Elena Gilbert?', 'Nina Dobrev');
criaCartao('Tema', 'Qual é o nome da cidade onde a série se passa?', 'Mystic Falls');
criaCartao('Tema', 'Qual é o nome do irmão de Stefan?', 'Damon Salvatore');
criaCartao('Tema', 'Quem transforma Caroline Forbes em vampira?', 'Damon Salvatore');
criaCartao('Tema', 'Quem é a melhor amiga de Elena?', 'Bonnie Bennett');
criaCartao('Tema', 'Qual é o nome da vilã original da 3ª temporada?', 'Klaus Mikaelson');
criaCartao('Tema', 'Quem é o doppelgänger de Elena?', 'Katherine Pierce');
criaCartao('Tema', 'Qual é o nome do bar frequentado pelos personagens?', 'Mystic Grill');
criaCartao('Tema', 'Quem é o caçador de vampiros original?', 'Alaric Saltzman');
criaCartao('Tema', 'Qual é o nome da família de vampiros originais?', 'Mikaelson');
criaCartao('Tema', 'Quem interpreta Damon Salvatore?', 'Ian Somerhalder');
criaCartao('Tema', 'Quem é o fundador da linha de bruxas Bennetts?', 'Emily Bennett');
criaCartao('Tema', 'Qual é o apelido de Klaus para Caroline?', 'Love');
criaCartao('Tema', 'Qual é o nome do irmão mais novo dos Salvatore?', 'Zach Salvatore');
criaCartao('Tema', 'Quem é o híbrido original?', 'Klaus Mikaelson');
criaCartao('Tema', 'Quem transforma Vicki Donovan em vampira?', 'Damon Salvatore');
criaCartao('Tema', 'Qual é o nome verdadeiro de Katherine Pierce?', 'Katerina Petrova');
criaCartao('Tema', 'Qual é a profissão de Alaric Saltzman?', 'Professor de história');
criaCartao('Tema', 'Quem se sacrifica no final da série?', 'Stefan Salvatore');
criaCartao('Tema', 'Qual é o nome do caçador que protege Elena na 4ª temporada?', 'Connor Jordan');
criaCartao('Tema', 'Qual é o nome da mãe de Bonnie?', 'Abby Bennett');
criaCartao('Tema', 'Quem traz Jeremy de volta à vida na 4ª temporada?', 'Bonnie Bennett');
criaCartao('Tema', 'Quem é o pai biológico de Elena?', 'John Gilbert');
criaCartao('Tema', 'Quem interpreta Stefan Salvatore?', 'Paul Wesley');
criaCartao('Tema', 'Quem é o melhor amigo humano de Matt Donovan?', 'Tyler Lockwood');
criaCartao('Tema', 'Qual é a organização que caça vampiros?', 'The Augustine Society');
criaCartao('Tema', 'Qual é o nome do médico que ajuda Damon?', 'Dr. Wes Maxfield');
criaCartao('Tema', 'Quem salva Elena de um acidente de carro no começo da série?', 'Stefan Salvatore');
criaCartao('Tema', 'Quem se torna um vampiro no final da 1ª temporada?', 'Caroline Forbes');
criaCartao('Tema', 'Quem é o lobisomem mais próximo de Klaus?', 'Tyler Lockwood');
criaCartao('Tema', 'Quem é a líder dos viajantes?', 'Markos');
criaCartao('Tema', 'Quem é a governanta dos Salvatore?', 'Liz Forbes');
criaCartao('Tema', 'Quem morre ao lado de Katherine no passado?', 'Emily Bennett');
criaCartao('Tema', 'Quem descobre o segredo dos Salvatore primeiro?', 'Vicki Donovan');
criaCartao('Tema', 'Qual é a relação entre Stefan e Damon?', 'Irmãos');
criaCartao('Tema', 'Quem ajuda a derrotar Klaus?', 'Elijah Mikaelson');
criaCartao('Tema', 'Quem é a bruxa que guia Bonnie?', 'Grams (Sheila Bennett)');
criaCartao('Tema', 'Quem é o líder do Conselho dos Fundadores?', 'Richard Lockwood');
criaCartao('Tema', 'Quem destrói o outro lado?', 'Bonnie Bennett');
criaCartao('Tema', 'Quem Elena escolhe no final da série?', 'Damon Salvatore');
criaCartao('Tema', 'Quem cria os anéis do dia para os vampiros?', 'Emily Bennett');
criaCartao('Tema', 'Qual é o nome da irmã de Matt Donovan?', 'Vicki Donovan');
criaCartao('Tema', 'Quem é a ex-noiva de Damon?', 'Rose');
criaCartao('Tema', 'Quem é o pai adotivo de Elena?', 'Grayson Gilbert');
criaCartao('Tema', 'Quem mata Jeremy temporariamente na 2ª temporada?', 'Damon Salvatore');
criaCartao('Tema', 'Quem é o guardião dos Salvatore no começo da série?', 'Zach Salvatore');
criaCartao('Tema', 'Quem é o primeiro a descobrir que Elena é um doppelgänger?', 'Stefan Salvatore');
criaCartao('Tema', 'Quem é a mulher original que ajudou a criar os vampiros?', 'Esther Mikaelson');
criaCartao('Tema', 'Qual é a ligação entre Caroline e Klaus?', 'Caroline é alvo do interesse amoroso de Klaus');

